version: '2.1'
services:

  sc-nginx:
    depends_on:
      - sc-app
    image: sah/sc-nginx:${SC_ENV}
    container_name: sc-nginx
    hostname: sc-nginx
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/centos/squirrel/nginx:/etc/nginx/conf.d:ro
      - /mnt/data/letsencrypt/etc:/etc/letsencrypt
      - /mnt/data/letsencrypt/www:/var/www/letsencrypt
    networks:
      sc-net:
        aliases:
          - nginx
    environment:
      - TZ=UTC

  sc-smtp:
    image: sah/sc-smtp:${SC_ENV}
    container_name: sc-smtp
    restart: on-failure
    environment:
      # For use with exim
      AWS_REGION: "us-east-1"
      SMTP_USERNAME: ${SC_SMTP_USERNAME}
      SMTP_PASSWORD: ${SC_SMTP_PASSWORD}
      # For use with the postfix container instead
#      ID: ${SC_SMTP_USERNAME}
#      KEY: ${SC_SMTP_PASSWORD}
#      FROM: sales@hoffman-house.com
#      HOSTNAME: www.hoffman-house.com
    networks:
      sc-net:
        aliases:
          - smtp
    expose:
      - 25

  sc-mysql:
    image: sah/sc-mysql:${SC_ENV}
    container_name: sc-mysql
    restart: on-failure
    environment:
      MYSQL_DATABASE: "squirrelcart"
      MYSQL_USER: "squirrelcart"
      MYSQL_PASSWORD: "squirrelcart"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - /mnt/data/mysql:/var/lib/mysql
    networks:
      sc-net:
        aliases:
          - db
          - mysql
    expose:
      - 3306

  sc-app:
    depends_on:
      - sc-smtp
      - sc-mysql
    image: sah/sc-app:${SC_ENV}
    container_name: sc-app
    environment:
      - APACHE_SERVER_NAME=hh-app.${SC_ENV}.hoffman-house.com
      - HOSTNAME=www.hoffman-house.com
    restart: on-failure
    networks:
      sc-net:
        aliases:
          - squirrelcart
          - app
    ports:
      - 8080:8080
      - 8443:8443

#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin:4.7
#    depends_on:
#      - sc-mysql
#    container_name: sc-phpmyadmin
#    environment:
#      PMA_ARBITRARY: 1
#      PMA_HOST: "mysql"
#      PMA_USER: "root"
#      PMA_PASSWORD: "root"
#    restart: on-failure
#    networks:
#      sc-net:
#        aliases:
#          - admin
#    ports:
#      - 8000:8000

networks:
  sc-net:
    driver: bridge
